###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

rotaryskills-mailhog:
  image: phpdockerio/mailhog:latest
  container_name: rotaryskills-mailhog
  ports:
    - "8125:8025"

rotaryskills-mysql:
  image: mysql:5.7
  container_name: rotaryskills-mysql
  volumes:
      - /var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
  ports:
    - "8106:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

rotaryskills-nginx:
  image: phpdockerio/nginx:latest
  container_name: rotaryskills-nginx
  volumes:
      - ../rotaryskills:/var/www/rotaryskills
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8180:80"
  links:
   - rotaryskills-php-fpm

rotaryskills-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: rotaryskills-php-fpm
  volumes:
    - ../rotaryskills:/var/www/rotaryskills
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - rotaryskills-mailhog
    - rotaryskills-mysql
